import { PDFDocument, rgb } from 'pdf-lib';

export async function exportModifiedPdf(originalArrayBuffer, objects, pageDimensions) {
  try {
    console.log("EXPORT: starting");
    console.log("EXPORT: source PDF bytes", {
      type: originalArrayBuffer?.constructor?.name,
      byteLength: originalArrayBuffer?.byteLength
    });

    console.log("EXPORT BUFFER BEFORE PDF-LIB", {
      byteLength: originalArrayBuffer?.byteLength,
      firstBytes: originalArrayBuffer
        ? Array.from(new Uint8Array(originalArrayBuffer.slice(0, 5)))
        : null
    });

    console.log("EXPORT: objects", objects);
    console.log("EXPORT: pageDimensions", pageDimensions);

    if (!originalArrayBuffer || originalArrayBuffer.byteLength === 0) {
      throw new Error("Original PDF array buffer is missing or detached/empty.");
    }

    const pdfDoc = await PDFDocument.load(originalArrayBuffer);
    const pages = pdfDoc.getPages();
    console.log("EXPORT: page count", pdfDoc?.getPageCount?.());

    for (const obj of objects || []) {
      const pageIndex = (obj.pageNumber || 1) - 1;
      if (pageIndex < 0 || pageIndex >= pages.length) continue;

      // Validate numeric coordinates
      if (!Number.isFinite(obj.x) || !Number.isFinite(obj.y) || !Number.isFinite(obj.width) || !Number.isFinite(obj.height) ||
          Number.isNaN(obj.x) || Number.isNaN(obj.y) || Number.isNaN(obj.width) || Number.isNaN(obj.height)) {
        console.error("Invalid numeric coordinates for object:", obj);
        continue;
      }

      const page = pages[pageIndex];
      const { width: pageWidth, height: pageHeight } = page.getSize();
      const rotation = page.getRotation?.()?.angle || 0;

      let effectiveWidth = pageWidth;
      let effectiveHeight = pageHeight;
      if (rotation === 90 || rotation === 270) {
        effectiveWidth = pageHeight;
        effectiveHeight = pageWidth;
      }

      const dim = pageDimensions[obj.pageNumber] || { width: effectiveWidth, height: effectiveHeight };
      const scaleX = effectiveWidth / dim.width;
      const scaleY = effectiveHeight / dim.height;

      const pdfX = obj.x * scaleX;
      // PDF Y is from bottom, canvas Y is from top
      const pdfY = effectiveHeight - ((obj.y + obj.height) * scaleY);
      const pdfWidth = obj.width * scaleX;
      const pdfHeight = obj.height * scaleY;

      try {
        if (obj.type === 'whiteout') {
          page.drawRectangle({
            x: pdfX,
            y: pdfY,
            width: pdfWidth,
            height: pdfHeight,
            color: rgb(1, 1, 1),
            borderColor: rgb(1, 1, 1),
          });
        } else if (obj.type === 'text') {
          const fontSize = (obj.style?.fontSize || 16) * scaleX;
          page.drawText(obj.content || '', {
            x: pdfX,
            y: pdfY + (pdfHeight / 4), // vertical alignment adjustment
            size: fontSize,
            color: rgb(0, 0, 0),
          });
        } else if (obj.type === 'signature') {
          if (obj.content && typeof obj.content === 'string' && obj.content.includes(',')) {
            const base64Data = obj.content.split(',')[1];
            if (base64Data) {
              const pngImageBytes = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));
              const pngImage = await pdfDoc.embedPng(pngImageBytes);
              page.drawImage(pngImage, {
                x: pdfX,
                y: pdfY,
                width: pdfWidth,
                height: pdfHeight,
              });
            }
          } else {
            console.warn("Invalid or missing signature content data URL for object:", obj.id);
          }
        }
      } catch (objErr) {
        console.error("Failed exporting object:", {
          id: obj.id,
          type: obj.type,
          pageNumber: obj.pageNumber,
          x: obj.x,
          y: obj.y,
          width: obj.width,
          height: obj.height,
          error: objErr?.message
        });
        throw objErr;
      }
    }

    const modifiedPdfBytes = await pdfDoc.save();
    console.log("EXPORT: generated bytes length", modifiedPdfBytes.length);
    return modifiedPdfBytes;
  } catch (error) {
    console.error("PDF EXPORT FAILED:", error);
    console.error("PDF EXPORT STACK:", error?.stack);
    throw error;
  }
}
